package com.tian.adapter.meta.scheme;

public enum Type {
    BIGINT,
    BINARY, BIT, BLOB,
    BOOLEAN, CHAR, CLOB, DATE, DECIMAL,
    DOUBLE, FLOAT, INTEGER, JAVA_OBJECT,
    LONGNVARCHAR,
    LONGVARBINARY, LONGVARCHAR, NCHAR,
    NCLOB, NUMERIC, NVARCHAR, OTHER, REAL,
    SMALLINT, TIME, TIMESTAMP, TINYINT, VARBINARY, VARCHAR;
}
